---
- name: install git
  homebrew:
      name: git
      state: present

- name: install ripgrep
  homebrew:
      name: ripgrep
      state: present

- name: install python3
  homebrew:
    name: python3
    state: present

- name: install coreutils
  homebrew:
    name: coreutils
    state: present

