---
- name: install git
  apt:
    name: git
    state: present
  become: yes

- name: install python
  apt:
    name: python2,python2-dev,python3,python3-dev,python3-pip
    state: present
  become: yes
