---
- name: Install common dev tools
  include_tasks: "{{ ansible_os_family|lower }}.yaml"

- name: Clone devlife
  git:
    repo: 'git@github.com:ahmedshuhel/devlife.git'
    dest: "{{ devlife_dir }}"

- name: Clone dotfiles
  git:
    repo: 'git@github.com:ahmedshuhel/dotfiles.git'
    dest: "{{ dotfiles_dir }}"

- name: Clone devenv
  git:
    repo: 'git@github.com:ahmedshuhel/devenv.git'
    dest: "{{ devenv_dir }}"

- name: install tmuxp
  pip:
    name: tmuxp
    executable: pip3

- name: Install nvm
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
  args:
    creates: "{{ home_dir }}/.nvm/nvm.sh"

- name: Install pyenv
  shell: >
    curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
  args:
    creates: "{{ home_dir }}/.pyenv"

- name: Install oh-my-zsh
  shell: >
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: "{{ home_dir }}/.oh-my-zsh"

- name: Create tmuxp symlink
  file:
    src: "{{ devenv_dir }}/.tmuxp"
    dest: "{{ home_dir }}/.tmuxp"
    force: yes
    state: link

- name: Create template folder symlink
  file:
    src: "{{ dotfiles_dir }}/.dl"
    dest: "{{ home_dir }}/.dl"
    force: yes
    state: link

- name: Create tmux.conf symlink
  file:
    src: "{{ dotfiles_dir }}/.tmux.conf"
    dest: "{{ home_dir }}/.tmux.conf"
    force: yes
    state: link

- name: Create a symbolic link of .zshrc
  file:
    src: "{{ dotfiles_dir }}/.zshrc"
    dest: "{{ home_dir }}/.zshrc"
    force: yes
    state: link

- name: Create a symbolic link of .pyenv.zsh
  file:
    src: "{{ dotfiles_dir }}/.pyenv.zsh"
    dest: "{{ home_dir }}/.pyenv.zsh"
    force: yes
    state: link

- name: Create dircolors symlink
  file:
    src: "{{ dotfiles_dir }}/.dircolors"
    dest: "{{ home_dir }}/.dircolors"
    force: yes
    state: link

- name: Create .tidyrc symlink
  file:
    src: "{{ dotfiles_dir }}/.tidyrc"
    dest: "{{ home_dir }}/.tidyrc"
    force: yes
    state: link

- name: Create .gitconfig symlink
  file:
    src: "{{ dotfiles_dir }}/.gitconfig"
    dest: "{{ home_dir }}/.gitconfig"
    force: yes
    state: link

- name: Create lemon symlink
  file:
    src: "{{ dotfiles_dir }}/lemon.sh"
    dest: "{{ home_dir }}/lemon.sh"
    force: yes
    state: link

- name: Create lime (autossh) symlink
  file:
    src: "{{ dotfiles_dir }}/lime.sh"
    dest: "{{ home_dir }}/lime.sh"
    force: yes
    state: link

- name: Create start symlink
  file:
    src: "{{ dotfiles_dir }}/start.sh"
    dest: "{{ home_dir }}/start.sh"
    force: yes
    state: link


- name: Clone zsh auto suggestions
  git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions'
    dest: "{{ home_dir }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

- name: Clone zsh syntax highlighting
  git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: "{{ home_dir }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

- name: Clone zsh lazy load
  git:
    repo: 'https://github.com/qoomon/zsh-lazyload.git'
    dest: "{{ home_dir }}/.oh-my-zsh/custom/plugins/zsh-lazyload"
