---
- name: download neovim
  get_url:
    url: https://github.com/neovim/neovim/releases/download/v0.5.0/nvim.appimage
    dest: "{{local_bin_dir}}/nvim.appimage"
    mode: u+x

- name: install python3 pynvim
  pip:
    name: neovim
    executable: pip3

- name: create necessary directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ config_dir }}"

- name: Create a symbolic link (init.lua)
  file:
    src: "{{ dotfiles_dir }}/init.lua"
    dest: "{{ init_file }}"
    force: yes
    state: link

- name: Create a symbolic link (lua folder)
  file:
    src: "{{ dotfiles_dir }}/lua"
    dest: "{{ lua_dir }}"
    force: yes
    state: link
