---
- name: Install common dev tools
  include_tasks: "{{ ansible_os_family|lower }}.yaml"

- name: install python3 pynvim
  pip:
    name: neovim
    executable: pip3

- name: Create a symbolic link to nvim folder
  file:
    src: "{{ dotfiles_dir }}/nvim"
    dest: "{{ config_dir }}"
    force: yes
    state: link
